### PR TITLE
Add missing dependency

### LINKED ISSUE #5: Missing gulp-ignore dependency
Required here https://github.com/joecohens/laravel-elixir-requirejs/blob/master/index.js#L3
But not in the package.json

### PR DESCRIPTION
**Pull request by thomaswelton**
Fixes #5

### CODE REVIEW

**Comment by joecohens** [comment]
Hey! Thanks for the PR sorry I didn't read the issue before. Can you rollback these changes and instead remove the require in the index.js file, since gulpIgnore is not being used in this package. I've must have copy and pasted there. Thanks again!

**Comment by joecohens** [comment]
@thomaswelton Any movement here? Do you want me to do it?

**Comment by thomaswelton** [comment]
Yeah can do it. You should be able to edit the file directly in github and commit

**Comment by joecohens** [comment]
https://github.com/joecohens/laravel-elixir-requirejs/commit/e02a89113f1a91e43bfd04abcad813f866738930

**Pull request closed without merging**
